/** Mock data backing the stubbed client. Swap out once the real API lands. */

import type {
  Achievement,
  BucketItem,
  BucketListSummary,
  Comment,
  Conversation,
  ExploreMedia,
  Message,
  Notification,
  StreakSummary,
  User,
} from './types';

export const mockUser: User = {
  id: 'u_1',
  username: 'kunal',
  name: 'Kunal Mehra',
  avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
  bio: 'Collecting sunrises, summits, and a suspicious number of unfinished side projects.',
  verified: true,
  followersCount: 1284,
  followingCount: 342,
  listsCount: 12,
  completedCount: 47,
  createdAt: '2025-01-04T10:00:00Z',
};

export const mockUsers: User[] = [
  mockUser,
  {
    id: 'u_2',
    username: 'aria',
    name: 'Aria Fontaine',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    bio: 'Travel, film photography, and saying yes before I overthink it.',
    verified: false,
    followersCount: 8123,
    followingCount: 210,
    listsCount: 23,
    completedCount: 88,
    createdAt: '2024-11-12T10:00:00Z',
  },
  {
    id: 'u_3',
    username: 'devon',
    name: 'Devon Park',
    avatarUrl: 'https://randomuser.me/api/portraits/men/52.jpg',
    bio: 'Marathon in every continent. 4 down, a few knees to go.',
    verified: true,
    followersCount: 30214,
    followingCount: 91,
    listsCount: 7,
    completedCount: 132,
    createdAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'u_4',
    username: 'mira',
    name: 'Mira Patel',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    bio: 'Scuba, street food, and 11 passports stamps to go.',
    verified: false,
    followersCount: 4521,
    followingCount: 380,
    listsCount: 15,
    completedCount: 61,
    createdAt: '2025-03-19T10:00:00Z',
  },
  {
    id: 'u_5',
    username: 'theo',
    name: 'Theo Nakamura',
    avatarUrl: 'https://randomuser.me/api/portraits/men/76.jpg',
    bio: 'Climbing things I probably should not. Documenting the rest.',
    verified: true,
    followersCount: 19840,
    followingCount: 145,
    listsCount: 9,
    completedCount: 104,
    createdAt: '2024-09-22T10:00:00Z',
  },
  {
    id: 'u_6',
    username: 'lena',
    name: 'Lena Brooks',
    avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    bio: 'Coffee maps of every city. Slowly, then all at once.',
    verified: false,
    followersCount: 2310,
    followingCount: 512,
    listsCount: 31,
    completedCount: 73,
    createdAt: '2025-02-08T10:00:00Z',
  },
];

const userRef = (id: string) => {
  const u = mockUsers.find((x) => x.id === id) ?? mockUser;
  return {
    id: u.id,
    username: u.username,
    name: u.name,
    avatarUrl: u.avatarUrl,
    verified: u.verified,
  };
};

export const mockLists: BucketListSummary[] = [
  {
    id: 'l_1',
    title: 'Japan, finally',
    description: 'The trip we keep talking about and never book. This year it gets booked.',
    coverUrl: null,
    visibility: 'public',
    category: 'Travel',
    owner: { id: 'u_1', username: 'kunal', name: 'Kunal Mehra', avatarUrl: null, verified: true },
    collaborators: [{ id: 'u_2', avatarUrl: null, name: 'Aria Fontaine' }],
    itemsCount: 14,
    completedCount: 5,
    starsCount: 212,
    savedByMe: false,
    starredByMe: true,
    updatedAt: '2026-06-20T10:00:00Z',
  },
  {
    id: 'l_2',
    title: 'Things to do before 30',
    description: 'A countdown that is aging faster than I am.',
    coverUrl: null,
    visibility: 'public',
    category: 'Life',
    owner: { id: 'u_2', username: 'aria', name: 'Aria Fontaine', avatarUrl: null, verified: false },
    collaborators: [],
    itemsCount: 30,
    completedCount: 19,
    starsCount: 1893,
    savedByMe: true,
    starredByMe: false,
    updatedAt: '2026-06-18T10:00:00Z',
  },
  {
    id: 'l_3',
    title: 'Couch to first marathon',
    description: 'Documenting every blister so you do not have to.',
    coverUrl: null,
    visibility: 'public',
    category: 'Fitness',
    owner: { id: 'u_3', username: 'devon', name: 'Devon Park', avatarUrl: null, verified: true },
    collaborators: [],
    itemsCount: 8,
    completedCount: 8,
    starsCount: 4021,
    savedByMe: false,
    starredByMe: false,
    updatedAt: '2026-05-30T10:00:00Z',
  },
  {
    id: 'l_4',
    title: 'Learn to actually cook',
    description: 'Beyond pasta. The goal is one dish that impresses someone.',
    coverUrl: null,
    visibility: 'private',
    category: 'Life',
    owner: { id: 'u_1', username: 'kunal', name: 'Kunal Mehra', avatarUrl: null, verified: true },
    collaborators: [],
    itemsCount: 10,
    completedCount: 3,
    starsCount: 18,
    savedByMe: false,
    starredByMe: false,
    updatedAt: '2026-06-26T10:00:00Z',
  },
  {
    id: 'l_5',
    title: 'Weekend microadventures',
    description: 'One tiny adventure every weekend. Small trips, big dopamine.',
    coverUrl: null,
    visibility: 'public',
    category: 'Travel',
    owner: { id: 'u_1', username: 'kunal', name: 'Kunal Mehra', avatarUrl: null, verified: true },
    collaborators: [{ id: 'u_3', avatarUrl: null, name: 'Devon Park' }],
    itemsCount: 16,
    completedCount: 9,
    starsCount: 96,
    savedByMe: false,
    starredByMe: false,
    updatedAt: '2026-06-24T10:00:00Z',
  },
];

export const mockItems: BucketItem[] = [
  {
    id: 'i_1',
    listId: 'l_1',
    title: 'Watch sunrise from Mount Fuji',
    note: 'Book the mountain hut early, apparently it sells out fast.',
    status: 'dreaming',
    photos: [],
    location: 'Fujinomiya, Japan',
    targetDate: '2026-09-01T00:00:00Z',
    completedAt: null,
    position: 0,
  },
  {
    id: 'i_2',
    listId: 'l_1',
    title: 'Eat ramen at a 5-seat counter',
    note: null,
    status: 'completed',
    photos: [],
    location: 'Tokyo, Japan',
    targetDate: null,
    completedAt: '2026-06-10T00:00:00Z',
    position: 1,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c_1',
    author: {
      id: 'u_2',
      username: 'aria',
      name: 'Aria Fontaine',
      avatarUrl: null,
      verified: false,
    },
    body: 'Okay this just moved Japan to the top of my own list. Saving.',
    createdAt: '2026-06-21T08:30:00Z',
    likesCount: 12,
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: 'a_1',
    key: 'first_list',
    title: 'First Dream',
    description: 'Created your very first bucket list.',
    iconColor: '#ffbb00',
    unlockedAt: '2025-01-05T10:00:00Z',
    progress: 1,
  },
  {
    id: 'a_2',
    key: 'first_complete',
    title: 'Done and Dusted',
    description: 'Completed your first goal.',
    iconColor: '#ff006e',
    unlockedAt: '2025-02-01T10:00:00Z',
    progress: 1,
  },
  {
    id: 'a_3',
    key: 'trailblazer',
    title: 'Trailblazer',
    description: 'Kept a 30 day streak alive.',
    iconColor: '#ff7a00',
    unlockedAt: '2026-06-28T10:00:00Z',
    progress: 1,
  },
  {
    id: 'a_4',
    key: 'globetrotter',
    title: 'Globetrotter',
    description: 'Completed goals on 3 different continents.',
    iconColor: '#4d8bff',
    unlockedAt: '2026-04-14T10:00:00Z',
    progress: 1,
  },
  {
    id: 'a_5',
    key: 'hundred_followers',
    title: 'Crowd Favorite',
    description: 'Reached 100 followers.',
    iconColor: '#8b3dff',
    unlockedAt: null,
    progress: 0.62,
  },
  {
    id: 'a_6',
    key: 'collector',
    title: 'The Collector',
    description: 'Created 25 bucket lists.',
    iconColor: '#ff006e',
    unlockedAt: null,
    progress: 0.48,
  },
  {
    id: 'a_7',
    key: 'storyteller',
    title: 'Storyteller',
    description: 'Added photos to 50 completed goals.',
    iconColor: '#ffbb00',
    unlockedAt: null,
    progress: 0.34,
  },
  {
    id: 'a_8',
    key: 'centurion',
    title: 'Centurion',
    description: 'Completed 100 goals. No big deal.',
    iconColor: '#8b3dff',
    unlockedAt: null,
    progress: 0.47,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n_1',
    type: 'star',
    actor: userRef('u_2'),
    text: 'starred your bucket list "Japan, finally"',
    read: false,
    createdAt: '2026-06-30T08:40:00Z',
  },
  {
    id: 'n_2',
    type: 'follow',
    actor: userRef('u_3'),
    text: 'started following you',
    read: false,
    createdAt: '2026-06-30T07:15:00Z',
  },
  {
    id: 'n_3',
    type: 'comment',
    actor: userRef('u_4'),
    text: 'commented: "Adding this to mine immediately."',
    read: false,
    createdAt: '2026-06-29T21:05:00Z',
  },
  {
    id: 'n_4',
    type: 'collab_invite',
    actor: userRef('u_5'),
    text: 'invited you to collaborate on "Summit Club"',
    read: true,
    createdAt: '2026-06-29T14:30:00Z',
  },
  {
    id: 'n_5',
    type: 'achievement',
    actor: null,
    text: 'You unlocked the "Trailblazer" badge for a 30 day streak',
    read: true,
    createdAt: '2026-06-28T12:00:00Z',
  },
  {
    id: 'n_6',
    type: 'star',
    actor: userRef('u_6'),
    text: 'starred your bucket list "Weekend microadventures"',
    read: true,
    createdAt: '2026-06-27T18:22:00Z',
  },
  {
    id: 'n_7',
    type: 'progress',
    actor: userRef('u_3'),
    text: 'completed "Run a sub-4 marathon" on a list you follow',
    read: true,
    createdAt: '2026-06-26T09:10:00Z',
  },
];

const exploreCovers = [
  { url: 'photo-1469474968028-56623f02e42e', aspect: 1.25, cat: 'Travel' },
  { url: 'photo-1551632811-561732d1e306', aspect: 1.5, cat: 'Hiking' },
  { url: 'photo-1502082553048-f009c37129b9', aspect: 0.8, cat: 'Travel' },
  { url: 'photo-1530549387789-4c1017266635', aspect: 1.33, cat: 'Fitness' },
  { url: 'photo-1500530855697-b586d89ba3ee', aspect: 0.9, cat: 'Travel' },
  { url: 'photo-1476514525535-07fb3b4ae5f1', aspect: 1.4, cat: 'Hiking' },
  { url: 'photo-1507525428034-b723cf961d3e', aspect: 0.75, cat: 'Travel' },
  { url: 'photo-1504280390367-361c6d9f38f4', aspect: 1.2, cat: 'Camping' },
  { url: 'photo-1486870591958-9b9d0d1dda99', aspect: 1.0, cat: 'Food' },
  { url: 'photo-1533105079780-92b9be482077', aspect: 1.45, cat: 'Travel' },
  { url: 'photo-1518609878373-06d740f60d8b', aspect: 0.8, cat: 'Fitness' },
  { url: 'photo-1455620611406-966ca6889d80', aspect: 1.3, cat: 'Adventure' },
  { url: 'photo-1464822759023-fed622ff2c3b', aspect: 1.1, cat: 'Hiking' },
  { url: 'photo-1493246507139-91e8fad9978e', aspect: 0.85, cat: 'Travel' },
  { url: 'photo-1528127269322-539801943592', aspect: 1.5, cat: 'Food' },
  { url: 'photo-1501785888041-af3ef285b470', aspect: 1.2, cat: 'Travel' },
  { url: 'photo-1483683804023-6ccdb62f86ef', aspect: 0.9, cat: 'Adventure' },
  { url: 'photo-1510797215324-95aa89f43c33', aspect: 1.35, cat: 'Camping' },
  { url: 'photo-1522163182402-834f871fd851', aspect: 1.0, cat: 'Travel' },
  { url: 'photo-1469854523086-cc02fe5d8800', aspect: 1.4, cat: 'Adventure' },
  { url: 'photo-1454942901704-3c44c11b2ad1', aspect: 0.8, cat: 'Fitness' },
  { url: 'photo-1519681393784-d120267933ba', aspect: 1.25, cat: 'Camping' },
];

const exploreTitles = [
  'Sunrise over the Torii gates',
  'Day 14 on the Pacific Crest Trail',
  'We finally booked the Iceland trip',
  'First sub-4 marathon, documented',
  'Slept under the Milky Way in Wadi Rum',
  'Every ramen counter in Tokyo, ranked',
  'Free-diving with no plan and a GoPro',
  'Van life, week one: everything broke',
  'Made pasta from scratch for once',
  'The summit push at 4am',
  'Northern lights, finally, on the third try',
  'Cherry blossom season, no filter needed',
];

export const mockExplore: ExploreMedia[] = exploreCovers.map((c, i) => {
  const author = mockUsers[(i % (mockUsers.length - 1)) + 1];
  return {
    id: `x_${i + 1}`,
    type: i % 3 === 0 ? 'video' : 'image',
    thumbnailUrl: `https://images.unsplash.com/${c.url}?auto=format&fit=crop&w=600&q=70`,
    aspect: c.aspect,
    title: exploreTitles[i % exploreTitles.length],
    author: {
      id: author.id,
      username: author.username,
      name: author.name,
      avatarUrl: author.avatarUrl,
      verified: author.verified,
    },
    starsCount: Math.round(120 + ((i * 197) % 4200)),
    viewsCount: Math.round(2400 + ((i * 5113) % 180000)),
    durationSeconds: i % 3 === 0 ? 8 + ((i * 7) % 52) : null,
    category: c.cat,
  };
});

export const mockStreak: StreakSummary = {
  current: 34,
  longest: 58,
  freezesAvailable: 2,
  weeklyGoal: 5,
  thisWeekDone: 4,
  startedAt: '2026-05-27T00:00:00Z',
  // 126 days (18 weeks) of intensity, oldest first. A believable, slightly messy history.
  days: Array.from({ length: 126 }, (_, i) => {
    const recent = i > 91; // last 5 weeks are the active streak
    if (recent) return i % 17 === 0 ? 0 : 1 + ((i * 7) % 4);
    if (i % 5 === 0) return 0;
    return (i * 3) % 5;
  }),
  milestones: [
    { days: 7, label: 'First Week', reached: true },
    { days: 14, label: 'Fortnight', reached: true },
    { days: 30, label: 'Trailblazer', reached: true },
    { days: 50, label: 'Unstoppable', reached: false },
    { days: 100, label: 'Centurion', reached: false },
    { days: 365, label: 'Year of Dreams', reached: false },
  ],
};

export const mockConversations: Conversation[] = [
  {
    id: 'cv_1',
    participant: userRef('u_2'),
    lastMessage: 'Okay sending you the Kyoto itinerary tonight, it is unhinged.',
    lastAt: '2026-06-30T09:12:00Z',
    unread: 2,
    online: true,
  },
  {
    id: 'cv_2',
    participant: userRef('u_3'),
    lastMessage: 'You: long run sunday? 18k, no excuses',
    lastAt: '2026-06-30T07:40:00Z',
    unread: 0,
    online: true,
  },
  {
    id: 'cv_3',
    participant: userRef('u_5'),
    lastMessage: 'The permits came through for the summit. We are GO.',
    lastAt: '2026-06-29T20:05:00Z',
    unread: 0,
    online: false,
  },
  {
    id: 'cv_4',
    participant: userRef('u_4'),
    lastMessage: 'wait you actually did the freedive?? tell me everything',
    lastAt: '2026-06-28T15:30:00Z',
    unread: 0,
    online: false,
  },
  {
    id: 'cv_5',
    participant: userRef('u_6'),
    lastMessage: 'You: added that cafe to the Lisbon list',
    lastAt: '2026-06-27T11:18:00Z',
    unread: 0,
    online: false,
  },
];

export const mockMessages: Record<string, Message[]> = {
  cv_1: [
    {
      id: 'm_1',
      conversationId: 'cv_1',
      fromMe: false,
      body: 'Did you book the flights yet or are we still "thinking about it"',
      createdAt: '2026-06-30T08:50:00Z',
    },
    {
      id: 'm_2',
      conversationId: 'cv_1',
      fromMe: true,
      body: 'Booked. October 4th. It is real now, no take-backs.',
      createdAt: '2026-06-30T08:55:00Z',
    },
    {
      id: 'm_3',
      conversationId: 'cv_1',
      fromMe: false,
      body: 'AHHH finally',
      createdAt: '2026-06-30T08:56:00Z',
    },
    {
      id: 'm_4',
      conversationId: 'cv_1',
      fromMe: false,
      body: 'Okay sending you the Kyoto itinerary tonight, it is unhinged.',
      createdAt: '2026-06-30T09:12:00Z',
    },
  ],
  cv_2: [
    {
      id: 'm_5',
      conversationId: 'cv_2',
      fromMe: false,
      body: 'how are the legs feeling after thursday',
      createdAt: '2026-06-30T07:30:00Z',
    },
    {
      id: 'm_6',
      conversationId: 'cv_2',
      fromMe: true,
      body: 'long run sunday? 18k, no excuses',
      createdAt: '2026-06-30T07:40:00Z',
    },
  ],
  cv_3: [
    {
      id: 'm_7',
      conversationId: 'cv_3',
      fromMe: false,
      body: 'The permits came through for the summit. We are GO.',
      createdAt: '2026-06-29T20:05:00Z',
    },
  ],
  cv_4: [
    {
      id: 'm_8',
      conversationId: 'cv_4',
      fromMe: false,
      body: 'wait you actually did the freedive?? tell me everything',
      createdAt: '2026-06-28T15:30:00Z',
    },
  ],
  cv_5: [
    {
      id: 'm_9',
      conversationId: 'cv_5',
      fromMe: true,
      body: 'added that cafe to the Lisbon list',
      createdAt: '2026-06-27T11:18:00Z',
    },
  ],
};
